extends:
  - eslint:recommended
  - google

env:
  es6: true
  browser: true
  webextensions: true

{
    "env": {
        "browser": true,
        "es6": true,
        "webextensions": true
    },
    "extends": [
      "eslint:recommended",
      "google"
    ]
}